// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwB2Xfsyyw65j9tu9CaIQopb6VlyhRZvE',
    appId: '1:642673925936:web:cbf56d971f5ea9fef632f5',
    messagingSenderId: '642673925936',
    projectId: 'stylesnap-20daa',
    authDomain: 'stylesnap-20daa.firebaseapp.com',
    storageBucket: 'stylesnap-20daa.appspot.com',
    measurementId: 'G-X7V571DB51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysl7Ovi9FfIUyk3YFQOvrGf23zGULZVk',
    appId: '1:642673925936:android:5fd9f5cc09b5670ff632f5',
    messagingSenderId: '642673925936',
    projectId: 'stylesnap-20daa',
    storageBucket: 'stylesnap-20daa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwhYrBoAWQD-sdhOWOia9Q-GrEx5CNHw',
    appId: '1:642673925936:ios:653b7bc0e68b589ff632f5',
    messagingSenderId: '642673925936',
    projectId: 'stylesnap-20daa',
    storageBucket: 'stylesnap-20daa.appspot.com',
    iosBundleId: 'com.example.stylesnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwhYrBoAWQD-sdhOWOia9Q-GrEx5CNHw',
    appId: '1:642673925936:ios:653b7bc0e68b589ff632f5',
    messagingSenderId: '642673925936',
    projectId: 'stylesnap-20daa',
    storageBucket: 'stylesnap-20daa.appspot.com',
    iosBundleId: 'com.example.stylesnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwB2Xfsyyw65j9tu9CaIQopb6VlyhRZvE',
    appId: '1:642673925936:web:237e4d45c24eb589f632f5',
    messagingSenderId: '642673925936',
    projectId: 'stylesnap-20daa',
    authDomain: 'stylesnap-20daa.firebaseapp.com',
    storageBucket: 'stylesnap-20daa.appspot.com',
    measurementId: 'G-4GPH20B30B',
  );

}